[package]
name = "crab-rt"
version = "0.1.0"
authors = ["TrAyZeN <lbenitoproduction@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[dependencies]
image = "0.23.12"
rand = "0.7.3"

[dev-dependencies]
criterion = "0.3"
rayon = "1.5.0"

[[bench]]
name = "benchmark"
harness = false

[[bench]]
name = "multithreading"
harness = false
path = "benches/multithreading.rs"

[[bench]]
name = "rayon"
harness = false
path = "benches/rayon.rs"
